/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as PersonsIndexRouteImport } from './routes/persons.index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'
import { Route as PersonsIdRouteImport } from './routes/persons.$id'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as QuotesIdEditRouteImport } from './routes/quotes.$id.edit'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesRoute,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonsRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRoute,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServicesRoute,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuotesRoute,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PersonsRoute,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const QuotesIdEditRoute = QuotesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/persons': typeof PersonsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/packages/$id': typeof PackagesIdRoute
  '/persons/$id': typeof PersonsIdRoute
  '/quotes/$id': typeof QuotesIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/services/$id': typeof ServicesIdRoute
  '/packages/': typeof PackagesIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/quotes/$id/edit': typeof QuotesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packages/$id': typeof PackagesIdRoute
  '/persons/$id': typeof PersonsIdRoute
  '/quotes/$id': typeof QuotesIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/services/$id': typeof ServicesIdRoute
  '/packages': typeof PackagesIndexRoute
  '/persons': typeof PersonsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/quotes/$id/edit': typeof QuotesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/persons': typeof PersonsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/packages/$id': typeof PackagesIdRoute
  '/persons/$id': typeof PersonsIdRoute
  '/quotes/$id': typeof QuotesIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/services/$id': typeof ServicesIdRoute
  '/packages/': typeof PackagesIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/quotes/$id/edit': typeof QuotesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/packages'
    | '/persons'
    | '/quotes'
    | '/services'
    | '/packages/$id'
    | '/persons/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/services/$id'
    | '/packages/'
    | '/persons/'
    | '/quotes/'
    | '/services/'
    | '/quotes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/packages/$id'
    | '/persons/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/services/$id'
    | '/packages'
    | '/persons'
    | '/quotes'
    | '/services'
    | '/quotes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/packages'
    | '/persons'
    | '/quotes'
    | '/services'
    | '/packages/$id'
    | '/persons/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/services/$id'
    | '/packages/'
    | '/persons/'
    | '/quotes/'
    | '/services/'
    | '/quotes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PersonsRoute: typeof PersonsRouteWithChildren
  QuotesRoute: typeof QuotesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/persons/': {
      id: '/persons/'
      path: '/'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/quotes/$id/edit': {
      id: '/quotes/$id/edit'
      path: '/edit'
      fullPath: '/quotes/$id/edit'
      preLoaderRoute: typeof QuotesIdEditRouteImport
      parentRoute: typeof QuotesIdRoute
    }
  }
}

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

interface PersonsRouteChildren {
  PersonsIdRoute: typeof PersonsIdRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
}

const PersonsRouteChildren: PersonsRouteChildren = {
  PersonsIdRoute: PersonsIdRoute,
  PersonsIndexRoute: PersonsIndexRoute,
}

const PersonsRouteWithChildren =
  PersonsRoute._addFileChildren(PersonsRouteChildren)

interface QuotesIdRouteChildren {
  QuotesIdEditRoute: typeof QuotesIdEditRoute
}

const QuotesIdRouteChildren: QuotesIdRouteChildren = {
  QuotesIdEditRoute: QuotesIdEditRoute,
}

const QuotesIdRouteWithChildren = QuotesIdRoute._addFileChildren(
  QuotesIdRouteChildren,
)

interface QuotesRouteChildren {
  QuotesIdRoute: typeof QuotesIdRouteWithChildren
  QuotesNewRoute: typeof QuotesNewRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesIdRoute: QuotesIdRouteWithChildren,
  QuotesNewRoute: QuotesNewRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface ServicesRouteChildren {
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIdRoute: ServicesIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PersonsRoute: PersonsRouteWithChildren,
  QuotesRoute: QuotesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
