# Generated by Django 5.2.7 on 2026-02-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_quote_parent_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequoteperson',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='servicequoteperson',
            name='arrive_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicequoteperson',
            name='arrive_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicequoteperson',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicequoteperson',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
