# Generated by Django 5.2.7 on 2026-02-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_total_people'),
        ('quote', '0009_quote_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='group.group'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
