# Generated by Django 5.2.7 on 2026-03-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_people',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
