# Generated by Django 5.2.7 on 2025-10-09 03:48

import django.db.models.deletion
import shared.functions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('post', 'Post'), ('document', 'Document')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_files/', validators=[shared.functions.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
