# Generated by Django 5.2.7 on 2025-10-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0002_alter_media_options_rename_type_media_type_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='media',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
