# Generated by Django 5.2.7 on 2026-01-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text='Duration value'),
        ),
    ]
