# Generated by Django 5.2.7 on 2026-02-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
