# Generated by Django 5.2.7 on 2026-02-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_duration_service_duration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('group', 'Group'), ('private', 'Private'), ('arbitrary', 'Arbitrary')], default='group', max_length=50),
        ),
    ]
