# Generated by Django 5.2.7 on 2026-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_departure_time_pricerule_pricingtier'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tag.tag'),
        ),
    ]
