# Generated by Django 5.2.7 on 2026-02-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reference price for the service', max_digits=10),
        ),
    ]
