# Generated by Django 5.2.7 on 2025-10-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
