# Generated by Django 5.2.7 on 2026-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_total_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact_info',
            field=models.TextField(null=True),
        ),
    ]
