# Generated by Django 5.2.7 on 2025-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_total_people'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='person', to='group.group'),
        ),
    ]
