# Generated by Django 5.2.7 on 2025-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_total_people'),
        ('person', '0002_alter_person_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='person', to='group.group'),
        ),
    ]
