# Generated by Django 5.2.7 on 2026-02-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='group',
            new_name='groups',
        ),
    ]
