# Generated by Django 5.2.7 on 2025-10-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_total_people'),
        ('person', '0003_remove_person_groups_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='person', to='group.group'),
        ),
    ]
