# Generated by Django 5.2.7 on 2026-02-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_rename_group_person_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='groups',
            new_name='group',
        ),
    ]
