# Generated by Django 5.2.7 on 2026-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('low', 'baja'), ('medium', 'media'), ('hard', 'alta')], default='personal'),
        ),
    ]
