# Generated by Django 5.2.7 on 2026-02-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('low', 'baja'), ('medium', 'media'), ('hard', 'alta')], default='medium'),
        ),
    ]
