<<<<<<< HEAD:backend/api/todo/migrations/0003_alter_todo_priority.py
# Generated by Django 5.2.7 on 2026-02-01 18:02
=======
# Generated by Django 5.2.7 on 2026-02-05 04:05
>>>>>>> ebab8740b151d3c4f90000a40042b948473f81d7:backend/todo/migrations/0003_alter_todo_priority.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('low', 'baja'), ('medium', 'media'), ('hard', 'alta')], default='medium'),
        ),
    ]
