# Generated by Django 5.2.7 on 2025-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_quote_services_servicequoteperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequoteperson',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='servicequoteperson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
