# Generated by Django 5.2.7 on 2025-11-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_convert_servicequoteperson_id_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
