# Generated by Django 5.2.7 on 2025-11-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
