# Generated by Django 5.2.7 on 2025-11-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_alter_quote_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='parent_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='quote.quote'),
        ),
    ]
