# Generated by Django 5.2.7 on 2026-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_remove_servicequoteperson_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicequoteperson',
            name='arrive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicequoteperson',
            name='arrive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicequoteperson',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicequoteperson',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
