# Generated by Django 5.2.7 on 2026-03-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_alter_quote_group_alter_quote_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
