# Generated by Django 5.2.7 on 2026-02-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reference price for the package', max_digits=10),
        ),
    ]
