# Generated by Django 5.2.7 on 2025-10-16 00:38

import django.db.models.deletion
import shared.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='type_media',
        ),
        migrations.RemoveField(
            model_name='media',
            name='service',
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='media',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[shared.functions.validate_file_type]),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='media_media_content_c23fc6_idx'),
        ),
    ]
