# Generated by Django 5.2.7 on 2025-10-17 00:10

import shared.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_content_type_alter_media_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[shared.functions.validate_file_type, shared.functions.validate_image_type]),
        ),
    ]
