# Generated by Django 5.2.7 on 2025-10-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('group', '0002_alter_group_total_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='group.group'),
        ),
    ]
